{% set name = "glodap" %}
{% set version = "0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glodap-{{ version }}.tar.gz
  sha256: c2010963e7511fe1f0bc98ce82a0d2614b08dc61cf5ccbd3162e1c768e73f0eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - requests
    - scipy

test:
  imports:
    - glodap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'GLODAP downloader and importer in Python'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/glodap

extra:
  recipe-maintainers:
    - mvdh7
